home/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings


urlpatterns = [
    #path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('login/',views.user_login,name='user_login'),
    path('signup/',views.user_signup,name='user_signup'),
    path('donate/',views.donate,name='donate'),
    path('submit/',views.success,name='success'),
    #path('current/',views.current,name='current'),
    path('logout/',views.user_logout,name='user_logout'),
    path('gallary/',views.gallary2,name='gallary'),
    path('blog/',views.blog, name='blog'),
    path('upload/',views.upload, name='upload'),
    path('sitemap.xml',views.sitemap,name='sitemap'),





###EMAIL CONFIGURATION
#for changing password via email

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='home/reset_password_sent.html'),name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='home/reset_password.html'),name='password_reset_confirm'),
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name='home/changepass.html'), name='reset_password'),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='home/password_reset_confirm.html'),name='password_reset_complete'),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


# urlpatterns +=staticfiles_urlpatterns()

saksham_latest/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.conf import settings
from django.conf.urls.static import static
from django.forms import ModelForm
from django import forms

class Upload(models.Model):
    user=models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    id=models.AutoField(primary_key=True)
    applicat_name=models.CharField(max_length=50,blank=True,null=True)
    date_of_birth=models.DateField(auto_now_add=False,blank=True,null=True)
    gender=models.CharField(max_length=10,blank=True,null=True)
    email=models.EmailField(max_length=50,null=True)
    contact_number=models.DecimalField(max_digits=15,decimal_places=0,blank=False,null=True)
    upload = models.ImageField(upload_to='usermedia',null=True,blank=True)

    def __str__(self):
     return self.applicat_name






class gallary(models.Model):
    tittle=models.CharField(max_length = 30)
    url = models.URLField(blank=True)
    description = models.CharField(max_length=500)
    date=models.DateField(blank=False)
    image = models.ImageField(upload_to='Media')

home/forms.py
from django.forms import ModelForm
from . models import Upload
from . models import *


class ApplyForm(ModelForm):


    class Meta:
        model= Upload
        fields='__all__'
        exclude=['user']
# class ImageForm(object):
#     """docstring forImageForm."""
#
#
#
#     class Meta:
#         models = Images2
#         fields='__all__'
#









# class Notefullform(Noteform):
#     images =forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple':True}))
#     class Meta(Noteform.Meta):
#         fields=Noteform.Meta.fields + ['images',]

home/views.py
from django.shortcuts import render, redirect
from django.db import IntegrityError
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.models import auth,User
from django.contrib.auth.decorators import login_required
from .models import gallary , Upload
from django.forms import modelformset_factory
from . forms import ApplyForm
#from . models import  PostForm , ImageForm
from django.contrib import messages
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_protect

# Create your views here.
def home(request):
    return render(request,'home/index.html')
def success(request):
    return render (request,'home/submit.html')

def gallary2(request):
    G = gallary.objects.all()
    return render (request,'home/gallary.html',{'object':G})


@login_required(login_url='/login/')
def donate(request):
    return render(request,'home/donate.html')


def sitemap(request):
    return render (request,'home/sitemap.xml')
def blog(request):
    return render(request,'home/blog.html')

#APPLYING FORCE LOGIN with upload
@login_required(login_url='/login/')
@csrf_protect
def upload(request):
    print(" handeling uploads .............")
    #customer =request.user
    #form=ApplyForm(instance=customer)

    if request.method == 'POST':
        form=ApplyForm(request.POST,request.FILES)
        print(" handeling uploads2222222 .............")
        contex={'form':ApplyForm(),'error':'you have entered wrong creadentials, please provide correct information'}

        if form.is_valid():
            pro=form.save(commit=False)
            pro.user=request.user
            pro.save()
            return redirect('success')
        else:
            return render(request,'home/apply.html',contex)

    else:
           return render(request,'home/apply.html',{'form':ApplyForm()})







    # else:
    #     return render(request,'home/apply.html')








def user_logout(request):
      if request.method == 'POST':
         logout(request)
         return redirect('/')

def user_login(request):

    if request.method == 'POST':
        USERNAME = request.POST['username']
        PASSWORD = request.POST['password']
        x = authenticate(request,username=USERNAME, password=PASSWORD)

        if x is not None:

          login(request,x)
          return redirect('home')

        else:
          contex2={'hi':'invalid username or password'}
          return render(request,'home/joinus.html',{'hi':'Invalid Username or Password'})

    else:
        return render(request,'home/joinus.html')

def user_signup(request):

        if request.method == 'GET':
          return render(request, 'home/signup.html')
        else:

            username = request.POST['username']
            email = request.POST['email']
            password = request.POST['password']
            last_name = request.POST['re_type_password']
            if password == last_name:

             try:
                    user = User.objects.create_user(username=username, email=email, password=password)
                    user.save()

                    return redirect('user_login')
             except IntegrityError:
                    return render(request,'home/signup.html',
                                  {'error': 'username has used previously please try with another one'})


    # else:
    #             return render(request, 'signup.html', {'name': 'You entered wrong password , please try again'})

home/templates/home/apply.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Saksham is a NGO working towards making the families
    of the accused and prisoners in jail self independent economically so that they don't become
     the passive victim of punishment given by law.">
    <title>Saksham|Legal Aid Society</title>
    <link rel="preload stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" as="style">
    <link rel="preload stylesheet" href="https://fonts.googleapis.com/css2?family=Signika:wght@700&display=swap" as="style">
    <link rel="shortcut icon" href="{% static 'home/dist/img/favicon.ico'%}">
    <link rel="preload stylesheet" href="{% static 'home/stylesheets/font-face.css'%}" as="style">
    <link rel="stylesheet" href="{% static 'home/Depd/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'home/Depd/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/stylesheets/apply.css'%}">
    <link rel="stylesheet" href="{% static 'home/stylesheets/footer.css'%}">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark fixed-top">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-label="collapse button" >
              <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand mr-auto" href="#"><img src="{% static 'home/dist/img/kyan.png'%}" id="logo-image" alt="logo-image" loading="lazy">&nbsp;<span id="logo-text">Saksham</span></a>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'donate' %}">Donate</a>
                    </li>
                    <li class="nav-item active">
                    <a class="nav-link" href="{% url 'upload' %}">Apply<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        More...
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'blog' %}">BLog</a>
                        <a class="dropdown-item" href="{% url 'gallary' %}">Gallery</a>
                    </div>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <form method="post" action="{% url 'user_logout' %}">
                            {% csrf_token %}
                            <button class="nav-link btn btn-success">Logout</button>
                        </form>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link btn btn-warning" role="button" type="button" style="color: black;" href="{% url 'user_login' %}" id="nav-button">Join Us</a>
                    </li>
                    {% endif %}
              </ul>
            </div>
          </nav>
    </header>
    <div class="container" id="content">
        <div class="row">
            <div class="col-12" id="page-title">
                Application Form
            </div>
        </div>
        <div class="card">
            <img src="{% static 'home/dist/img/hands.png'%}" class="card-img-top img-fluid" alt="form-header">
            <div class="card-body">
                <form action="" method="POST" enctype="multipart/form-data">

                    <input type="hidden" name="csrfmiddlewaretoken" value="fTtwZ5ERKv56jcst3Q4NiXblo5EHw9k1QyHbDTjQumbml53za1V3kg02gKyBQwNC">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label class="col-sm-2 col-from-label" for="id_applicat_name" ><h5>Applicant Name</h5></label>
                        <div class="col-sm-10">
                            <input id="id_applicat_name" type="text" class="form-control" placeholder="Full Name" required="true" maxlength="50" name="aplicat_name">
                            <small id="applicat_name" class="form-text text-muted">
                                * Do not include Special Character eg:( /# .- @ _ \ .etc)
                            </small>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="id_date_of_birth"><h5>Date of Birth</h5></label>
                        <div class="col-sm-4">
                            <input id="id_date_of_birth" type="date" class="form-control" placeholder="DOB" name="date_of_birth">
                        </div>
                        <label class="offset-sm-2 col-sm-2 col-form-label" for="id_gender"><h5>Gender</h5></label>
                        <div class="col-sm-2">
                            <select id="id_gender" class="custom-select" id="id_gender">
                                <option selected>Choose..</option>
                                <option value="1">Male</option>
                                <option value="-1">Female</option>
                                <option value="0">Transgender</option>
                                <option value="-2">Prefer not to mention</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="id_contact_number" ><h5>Contact Number</h5></label>
                        <div  class="col-sm-4">
                            <input id="id_contact_number" class="form-control" type="tel" aria-describedby="phone number" required="true" name="contact_number" step="1">
                            <small id="phone" class="form-text text-muted">
                                * We won't share this with any third party.
                            </small>
                        </div>
                        <label class="offset-sm-1 col-sm-2 col-form-label" for="id_email"><h5>Email</h5></label>
                        <div class="col-sm-3">
                            <input id="id_email" class="form-control" type="email" maxlength="50" name="email" required>
                            <small id="phone2" class="form-text text-muted">
                                * We won't share this with any third party.
                            </small>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-form-label" for="image"><h5>Upload Your Passport size Photograph, Size must be Less Than 2mb</h5></label>
                    </div>
                    <div class="form-group row">
                        <div class="input-group">
                            <div class="custom-file">
                            <input type="file" class="custom-file-input" id="image" aria-describedby="inputGroupFileAddon04">
                            <label class="custom-file-label" for="image" id="choose">Choose file</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <button class="offset-sm-3 col-sm-2 col-12 btn btn-success" type="submit" role="button" style="margin-bottom: 1%;">Submit</button>
                        <button class="offset-sm-2 col-sm-2 col-12  btn btn-secondary" type="reset" role="button">Reset</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
    <footer>
        <div class="container-fluid" id="footer">
            <div  class="row">
                <div class="col-12" id="left-coloumn">
                    <img src="{% static 'home/dist/img/kyan.png'%}" class="footer-image d-block d-sm-none">
                    <span id="company-name">Saksham Foundation</span>
                </div>
            </div>
            <div class="row"id="right-coloumn">
              <div class="col-sm-4 col-12">
                <h2 id="email">Email</h2>
                  <a href="mailto:foundationssaksham@gmail.com"><h4>foundationssaksham@gmail.com</h4></a>
                </div>
            <div class="col-sm-4 col-12">
                <h2 id="phn">Contact</h2>
                <a href="tel:9674020035"><h4>+91-9674-02-0035</h4></a>
              </div>
            <div class="col-sm-4 d-none d-sm-block">
                <h2>Address</h2>
                <a href="#"><h4>B6, 4th Floor<br/>Coning Tower, Water Shed Area<br/>Citadel, Atlanta</h4></a>
              </div>
          </div>
          <div class="row" id="social">
              <div class="col-12"
                 <a  href="#"><span class="fa fa-facebook fa-lg" id="facebook"></span></a>
                 <a  href="#"><span class="fa fa-twitter fa-lg" id="twitter"></span></a>
                <a  href="#"><span class="fa fa-instagram fa-lg" id="instagram"></span></a>
            </div>
        </div>
     </div>
    </footer>
    <script src="{% static 'home/Depd/jquery.slim.min.js'%}"> </script>
    <script src="{% static 'home/Depd/popper.min.js'%}"></script>
    <script src="{% static 'home/Depd/bootstrap.min.js'%}"></script>
    <script src="{% static 'home/scripts/apply.js'%}"></script>
</body>
</html>

home/templates/home/blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-MKG5R2C');</script>
  <!-- End Google Tag Manager -->
  <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-176751443-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-176751443-2');
</script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-175902098-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-175902098-4');
</script>
<!-- starting code -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Saksham is a NGO working towards making the families
    of the accused and prisoners in jail self independent economically so that they don't become
     the passive victim of punishment given by law.">
    <title>Saksham | Legal Aid Society</title>
    <link rel="canonical" href="https://sakshamfoundations.in/" />
    <link rel="preload stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" as="style">
    <link rel="preload stylesheet" href="https://fonts.googleapis.com/css2?family=Work+Sans&display=swap" as="style">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Signika:wght@700&display=swap">
    <link rel="shortcut icon" href="{%static 'home/dist/img/favicon.ico'%}">
    <link rel="preload stylesheet" href="{%static 'home/stylesheets/font-face.css'%}" as="style">
    <link rel="stylesheet" href="{% static 'home/Depd/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'home/Depd/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/stylesheets/index.css'%}">
    <link rel="stylesheet" href="{% static 'home/stylesheets/footer.css'%}">
</head>
<body>
  <!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MKG5R2C"
  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <!-- End Google Tag Manager (noscript) -->
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark fixed-top">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-label="Collapse Button">
              <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand mr-auto" href="#"><img src="{%static 'home/dist/img/kyan.png'%}" loading="lazy" id="logo-image" alt="logo-image">&nbsp;<span id="logo-text">Saksham</span></a>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'donate' %}">Donate</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'upload' %}">Apply</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    More...
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">BLog</a>
                    <a class="dropdown-item" href="{% url 'gallary' %}">Gallery</a>
                  </div>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <form method="post" action="{% url 'user_logout' %}">

                        {% csrf_token %}
                        <button type="submit" class="btn btn-success" id="nav-button">Logout</button>
                    </form>
                </li>
               {% else %}
                <li class="nav-item">
                  <a class="nav-link btn btn-warning" type="button" style="color: black;" href="{% url 'user_login' %}" id="nav-button" name="login">Join Us</a>
                </li>
                {% endif %}
              </ul>
            </div>
          </nav>
    </header>

<br>
<br>
<br>
<br>
<br>
<br>


    <h> no recents blog <h>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>

<footer>
      <div class="container-fluid" id="footer">
          <div  class="row">
              <div class="col-12" id="left-coloumn">
                <img src="{% static 'home/dist/img/kyan.png'%}" class="footer-image d-block d-sm-none">
                  <span id="company-name">Saksham Foundation</span>
              </div>
          </div>
          <div class="row"id="right-coloumn">
              <div class="col-sm-4 col-6">
                <h2 id="email">Email</h2>
                      <a href="mailto:foundationssaksham@gmail.com"><h4>foundationssaksham@mail.com</h4></a>
              </div>
              <div class="col-sm-4 col-6">
                <h2 id="phn">Contact</h2>
                <a href="tel:9674020035"><h4>+91 96740 20035</h4></a>
              </div>
              <div class="col-sm-4 d-none d-sm-block">
                <h2>Address</h2>
                <a href="#"><h4>B6, 4th Floor<br/>62, CENTRAL ROAD, ANANDALOKE, P.O. SODEPUR <br/>KOLKATA 700110</h4></a>
              </div>
          </div>
          <div class="row" id="social">
              <div class="col-12">
                 <a  href="#"><span class="fa fa-facebook fa-lg" id="facebook"></span></a>
                  <a  href="#"><span class="fa fa-twitter fa-lg" id="twitter"></span></a>
                  <a  href="#"><span class="fa fa-instagram fa-lg" id="instagram"></span></a>
              </div>
          </div>
      </div>
      </footer>
      <script src="{% static 'home/Depd/jquery.slim.min.js'%}"> </script>
      <script src="{% static 'home/Depd/popper.min.js'%}"></script>
      <script src="{% static 'home/Depd/bootstrap.min.js'%}"></script>
      <script src="{% static 'home/scripts/index.js'%}"></script>
  </body>
  </html>

home/templates/home/changepass.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Change password</title>
</head>
<body>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

<p class="has-text-align-left has-text-color" style="font-size:59px;color:#24135f"><strong>Welcome to user support</strong></p>
<div class="wp-block-buttons"><!-- wp:button {"style":{"color":{"text":"#99e1d9","background":"#24135f"}}} -->

        <form method="post">{% csrf_token %}
            {{ form.p }}
            <fieldset class="module aligned">
    <div class="form-row field-email">
        <label for="id_email"> Write Your Registerd Email Address : </label>
        <br>
        <input type="email" name="email" autocomplete="email" maxlength="254" required id="id_email">
    </div>
    <br>
    <br>

    <input type="submit" value="  Reset my password">
  </fieldset>

        </form>
        <br>
<p ><strong>Remember your password ? want to try again ! </strong></p>

     <a href="{% url 'user_login' %}" type="submit" t>Let's login</a>
<div class="wp-block-button"><a class="wp-block-button__link has-text-color has-background" style="background-color:#24135f;color:#99e1d9"></a></div>
<!-- /wp:button --></div>
</body>
</html>

home/templates/home/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>successfully sent password </title>
</head>
<body>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>


<p class="has-text-align-left has-text-color" style="font-size:59px;color:#24135f"><strong>Welcome to user support</strong></p>
<div class="wp-block-buttons"><!-- wp:button {"style":{"color":{"text":"#99e1d9","background":"#24135f"}}} -->
   <br>
    <p ><strong><br>your password has been reseted succesfully , now please login </strong></p>
   <br>
    <a href="{% url 'user_login' %}" type="button">Login Page</a>
<div class="wp-block-button"><a class="wp-block-button__link has-text-color has-background" style="background-color:#24135f;color:#99e1d9"></a></div>
<!-- /wp:button --></div>
</body>
</html>
</body>
</html>